# Generated by Django 3.1.6 on 2021-02-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'supervisor')], default=2),
        ),
    ]
