# Generated by Django 3.1.6 on 2021-04-01 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20210207_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='teacher_info',
            old_name='subject',
            new_name='name',
        ),
        migrations.AddField(
            model_name='student_info',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Course_Info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('Student_Info', models.ManyToManyField(to='API.Student_Info')),
                ('Supervisor_Info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.supervisor_info')),
                ('Teacher_Info', models.ManyToManyField(to='API.Teacher_Info')),
            ],
        ),
        migrations.AddField(
            model_name='supervisor_info',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.department'),
        ),
        migrations.AddField(
            model_name='teacher_info',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.department'),
        ),
    ]
