# Generated by Django 3.1.6 on 2021-04-01 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20210401_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='supervisor_info',
            name='department',
        ),
        migrations.RemoveField(
            model_name='teacher_info',
            name='department',
        ),
        migrations.DeleteModel(
            name='department',
        ),
        migrations.AddField(
            model_name='supervisor_info',
            name='departments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.departments'),
        ),
        migrations.AddField(
            model_name='teacher_info',
            name='departments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.departments'),
        ),
    ]
