# Generated by Django 3.1.6 on 2021-04-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_student_info_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='semester',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
