# Generated by Django 3.1.6 on 2021-04-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20210402_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_info',
            name='semester',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
