# Generated by Django 3.1.6 on 2021-04-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20210402_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='semester',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
