# Generated by Django 3.1.6 on 2021-04-02 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_auto_20210402_2223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_Info',
        ),
    ]
