# Generated by Django 3.1.6 on 2021-04-02 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_course_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_Info',
        ),
    ]
