# Generated by Django 3.1.6 on 2021-04-02 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_course_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_info',
            name='semester',
        ),
    ]
