# Generated by Django 3.1.6 on 2021-04-03 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_auto_20210403_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_info',
            name='Student_Info',
            field=models.ManyToManyField(to='API.Student_Info'),
        ),
        migrations.AddField(
            model_name='course_info',
            name='Supervisor_Info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.supervisor_info'),
        ),
        migrations.AddField(
            model_name='course_info',
            name='Teacher_Info',
            field=models.ManyToManyField(to='API.Teacher_Info'),
        ),
        migrations.AddField(
            model_name='course_info',
            name='semester',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course_info',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
