# Generated by Django 3.1.6 on 2021-04-03 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_auto_20210403_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_info',
            name='Student_Info',
        ),
        migrations.RemoveField(
            model_name='course_info',
            name='Supervisor_Info',
        ),
        migrations.RemoveField(
            model_name='course_info',
            name='Teacher_Info',
        ),
        migrations.RemoveField(
            model_name='course_info',
            name='semester',
        ),
        migrations.AddField(
            model_name='course_info',
            name='departments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.departments'),
        ),
        migrations.CreateModel(
            name='Semester_Info',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('Course_Info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.course_info')),
                ('Student_Info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.student_info')),
                ('Teacher_Info', models.ManyToManyField(to='API.Teacher_Info')),
            ],
        ),
    ]
