# Generated by Django 3.1.6 on 2021-04-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_auto_20210403_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester_info',
            name='Teacher_Info',
        ),
    ]
