# Generated by Django 3.1.6 on 2021-04-03 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_remove_semester_info_teacher_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester_info',
            name='Student_Info',
        ),
        migrations.AddField(
            model_name='student_info',
            name='Semester_Info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.semester_info'),
        ),
    ]
