# Generated by Django 3.1.6 on 2021-04-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0022_auto_20210403_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester_info',
            name='Course_Info',
        ),
        migrations.AddField(
            model_name='semester_info',
            name='Course_Info',
            field=models.ManyToManyField(to='API.Course_Info'),
        ),
    ]
