# Generated by Django 3.1.6 on 2021-04-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0023_auto_20210403_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_info',
            name='Course_Info',
            field=models.ManyToManyField(to='API.Course_Info'),
        ),
    ]
