# Generated by Django 3.1.6 on 2021-04-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_auto_20210403_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_info',
            old_name='Courses',
            new_name='Semester_Info',
        ),
        migrations.RemoveField(
            model_name='student_info',
            name='semester_number',
        ),
    ]
