# Generated by Django 3.1.6 on 2021-04-06 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0026_auto_20210403_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester_info',
            name='Course_Info',
        ),
        migrations.RemoveField(
            model_name='student_info',
            name='Semester_Info',
        ),
        migrations.AddField(
            model_name='course_info',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.semester_info'),
        ),
        migrations.AddField(
            model_name='student_info',
            name='semester_number',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
