# Generated by Django 3.1.6 on 2021-04-06 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0027_auto_20210406_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='semester_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.semester_info'),
        ),
    ]
