# Generated by Django 3.1.6 on 2021-04-06 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0028_auto_20210406_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='grade',
        ),
        migrations.AddField(
            model_name='course_info',
            name='TodoList',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('Student_Info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.student_info')),
                ('Supervisor_Info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.supervisor_info')),
                ('Teacher_Info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.teacher_info')),
            ],
        ),
    ]
