# Generated by Django 3.1.6 on 2021-04-06 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0030_auto_20210406_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='Supervisor_Info',
            new_name='Course_Info',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='Teacher_Info',
        ),
    ]
