# Generated by Django 3.1.6 on 2021-04-06 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0031_auto_20210406_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='Course_Info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.course_info'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
