# Generated by Django 3.1.6 on 2021-04-06 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0033_auto_20210406_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='Student_Info',
            new_name='Student',
        ),
    ]
