# Generated by Django 3.1.6 on 2021-04-10 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0034_auto_20210406_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='course_info',
            name='TodoList',
        ),
        migrations.RemoveField(
            model_name='teacher_info',
            name='Course_Info',
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=100)),
                ('Class', models.ManyToManyField(to='API.ClassName')),
                ('Course_Info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.course_info')),
                ('Teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.teacher_info')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.ManyToManyField(to='API.ClassName')),
                ('Course_Info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.course_info')),
                ('Teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.teacher_info')),
            ],
        ),
        migrations.AddField(
            model_name='student_info',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.classname'),
        ),
    ]
