# Generated by Django 3.2 on 2021-04-11 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0036_auto_20210411_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherclasses',
            name='Class',
        ),
        migrations.AddField(
            model_name='teacherclasses',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.classname'),
        ),
    ]
