# Generated by Django 3.2 on 2021-04-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0037_auto_20210411_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor_info',
            old_name='departments',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='teacher_info',
            old_name='departments',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='supervisor_info',
            name='subject',
        ),
    ]
