# Generated by Django 3.2 on 2021-04-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0040_auto_20210420_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='final',
        ),
        migrations.AddField(
            model_name='grade',
            name='finalmark',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='coursework',
            field=models.FloatField(null=True),
        ),
    ]
