# Generated by Django 3.2 on 2021-04-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0041_auto_20210420_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='finalmark',
        ),
    ]
