# Generated by Django 3.2 on 2021-04-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0043_alter_grade_coursework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='coursework',
        ),
    ]
