# Generated by Django 3.2 on 2021-04-20 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0045_auto_20210420_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherclasses',
            name='Supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.supervisor_info'),
        ),
    ]
