# Generated by Django 3.1.6 on 2021-04-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0048_auto_20210421_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherclasses',
            name='Text',
            field=models.TextField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
