# Generated by Django 3.1.6 on 2021-04-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0049_auto_20210421_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherclasses',
            name='Text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.todolist'),
        ),
    ]
