# Generated by Django 3.1.6 on 2021-04-21 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0050_auto_20210421_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherclasses',
            name='Text',
        ),
        migrations.AddField(
            model_name='todolist',
            name='TeacherClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.teacherclasses'),
        ),
    ]
