# Generated by Django 3.1.6 on 2021-04-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0051_auto_20210421_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
