# Generated by Django 3.1.6 on 2021-04-22 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0052_auto_20210421_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='TeacherClass',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.teacherclasses'),
        ),
    ]
