# Generated by Django 3.1.6 on 2021-04-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0054_auto_20210422_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='TeacherClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.teacherclasses'),
        ),
    ]
