# Generated by Django 3.1.6 on 2021-04-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0055_auto_20210422_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='announce',
            field=models.BooleanField(default=False),
        ),
    ]
