# Generated by Django 3.1.6 on 2021-04-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0056_todolist_announce'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='level',
            field=models.CharField(choices=[('homework', 'HomeWork'), ('reminder', 'Reminder'), ('quiz', 'Quiz')], default='homework', max_length=8),
        ),
    ]
