# Generated by Django 3.1.6 on 2021-04-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0057_todolist_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
