# Generated by Django 3.1.6 on 2021-04-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0058_delete_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='link',
            field=models.CharField(max_length=360, null=True),
        ),
    ]
