# Generated by Django 3.1.6 on 2021-04-23 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0059_todolist_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='Student',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.student_info')),
                ('gardes', models.ManyToManyField(to='API.Grade')),
            ],
        ),
    ]
