# Generated by Django 3.1.6 on 2021-04-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0060_auto_20210423_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='gardes',
            new_name='grades',
        ),
    ]
