# Generated by Django 3.1.6 on 2021-04-23 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0061_auto_20210423_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.student_info'),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
