# Generated by Django 3.1.6 on 2021-04-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0064_auto_20210424_1713'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course_info',
            unique_together={('name', 'departments')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('Student', 'Course_Info')},
        ),
        migrations.AlterUniqueTogether(
            name='student_info',
            unique_together={('user', 'Class')},
        ),
        migrations.AlterUniqueTogether(
            name='supervisor_info',
            unique_together={('user', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='teacher_info',
            unique_together={('user', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherclasses',
            unique_together={('Teacher', 'Course_Info', 'Class')},
        ),
    ]
