# Generated by Django 3.1.6 on 2021-04-25 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0066_student_info_flag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('user', 'Course_Info')},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='Student',
        ),
    ]
