# Generated by Django 3.1.6 on 2021-04-25 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0067_auto_20210425_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='flag',
        ),
    ]
