# Generated by Django 3.1.6 on 2021-04-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0068_remove_student_info_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor_info',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
