# Generated by Django 3.1.6 on 2021-04-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0069_supervisor_info_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_info',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
