# Generated by Django 3.1.6 on 2021-04-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0073_remove_supervisor_info_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor_info',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
