# Generated by Django 3.1.6 on 2021-04-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0074_supervisor_info_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor_info',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='teacherclasses',
            unique_together={('Course_Info', 'Class')},
        ),
    ]
