# Generated by Django 3.1.6 on 2021-04-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0075_auto_20210425_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='level',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='link',
            field=models.CharField(blank=True, max_length=360, null=True),
        ),
    ]
